/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package npuzzle.gui;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author M-Art
 */
public class GUIChart extends javax.swing.JFrame {
    private GUIDataset dataset;
    private ChartPanel chpanel;
    /**
     * Creates new form GUIChart
     */
    public GUIChart(GUIDataset ds) {
        dataset = ds;
        initComponents();
        
        //----
        XYSeries min_series = new XYSeries("min-fit");
        int i = 0;
        for (double x : dataset.getMinFit()) {
            min_series.add(++i, x);
        }

        XYSeries max_series = new XYSeries("max-fit");
        i = 0;
        for (double x : dataset.getMaxFit()) {
            max_series.add(++i, x);
        }
        XYSeries avg_series = new XYSeries("avg-fit");
        i = 0;
        for (double x : dataset.getAvgFit()) {
            avg_series.add(++i, x);
        }

        XYSeriesCollection series = new XYSeriesCollection();
        series.addSeries(min_series);
        series.addSeries(max_series);
        series.addSeries(avg_series);

        JFreeChart chart = ChartFactory.createXYLineChart(null, null, null, series, PlotOrientation.VERTICAL, false, false, false);
        chpanel = new ChartPanel(chart);
        chpanel.setBounds(0, 0, jChartPanel.getSize().width, jChartPanel.getSize().height);
        chpanel.setVisible(true);
        jChartPanel.add(chpanel);
        jChartPanel.repaint();
        //---
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jChartPanel = new javax.swing.JPanel();

        jChartPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jChartPanelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jChartPanelLayout = new javax.swing.GroupLayout(jChartPanel);
        jChartPanel.setLayout(jChartPanelLayout);
        jChartPanelLayout.setHorizontalGroup(
            jChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jChartPanelLayout.setVerticalGroup(
            jChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChartPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jChartPanelComponentResized
        // TODO add your handling code here:
        chpanel.setBounds(0, 0, jChartPanel.getSize().width, jChartPanel.getSize().height);
    }//GEN-LAST:event_jChartPanelComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jChartPanel;
    // End of variables declaration//GEN-END:variables
}
