/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package npuzzle.gui;

import geneticalgorithm.Configuration;
import geneticalgorithm.GARouletteElitism;
import geneticalgorithm.GARouletteWheel;
import geneticalgorithm.GeneticAlgorithm;

/**
 *
 * @author M-Art
 */
public class GUIInfo extends javax.swing.JPanel {

    /**
     * Creates new form GUIInfo
     */
    public GUIInfo(Configuration conf, GeneticAlgorithm gen_alg, int dimension) {
        initComponents();
        doLayout();
        if(gen_alg instanceof GARouletteElitism)
            jGA.setText("Roulette Elitism");
        else if(gen_alg instanceof GARouletteWheel)
            jGA.setText("Roulette Wheel");
        jPuzzleSize.setText("" + dimension);
        jChromosomeLength.setText("" + conf.getChromosomeLength());
        jIterations.setText("" + conf.getIterations());
        jPopulationSize.setText("" + conf.getPopulationSize());
        jCrossoverRate.setText("" + conf.getCrossoverRate());
        jMutationRate.setText("" + conf.getMutationRate());
    }
    
    /**
     * Ustawia ilość iteracji widoczną na panelu na podaną w parametrze.
     * 
     * @param i ilość iteracji
     */
    public void setIterations(int i) {
        jIterations.setText(Integer.toString(i));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jGA = new javax.swing.JLabel();
        jPuzzleSize = new javax.swing.JLabel();
        jChromosomeLength = new javax.swing.JLabel();
        jPopulationSize = new javax.swing.JLabel();
        jCrossoverRate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jIterations = new javax.swing.JLabel();
        jIterationsCompleted = new javax.swing.JLabel();
        jMutationRate = new javax.swing.JLabel();

        jLabel2.setText("Rozmiar puzzli:");

        jLabel3.setText("Długość chromosomu:");

        jLabel4.setText("Wykonane iteracje:");

        jLabel5.setText("Wielkość populacji:");

        jLabel6.setText("Szansa krzyżowania:");

        jLabel8.setText("Szansa mutacji:");

        jLabel9.setText("Rodzaj algorytmu:");

        jGA.setText("null");

        jPuzzleSize.setText("0");

        jChromosomeLength.setText("0");

        jPopulationSize.setText("0");

        jCrossoverRate.setText("0");

        jLabel7.setText("Ilość iteracji:");

        jIterations.setText("0");

        jIterationsCompleted.setText("0");

        jMutationRate.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jIterations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPopulationSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCrossoverRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMutationRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuzzleSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jGA, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jChromosomeLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jIterationsCompleted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jGA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPuzzleSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jChromosomeLength))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jIterations))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPopulationSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCrossoverRate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMutationRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jIterationsCompleted)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jChromosomeLength;
    private javax.swing.JLabel jCrossoverRate;
    private javax.swing.JLabel jGA;
    private javax.swing.JLabel jIterations;
    private javax.swing.JLabel jIterationsCompleted;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jMutationRate;
    private javax.swing.JLabel jPopulationSize;
    private javax.swing.JLabel jPuzzleSize;
    // End of variables declaration//GEN-END:variables
}
